openapi: 3.2.0
info:
  title: Inference Service Readyz API
  version: 0.4.0
tags:
- name: Readyz
paths:
  /readyz:
    get:
      summary: Readyz
      operationId: readyz_readyz_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Readyz
components:
  securitySchemes:
    API_Key:
      type: http
      description: Bearer <api_key>
      scheme: bearer
