openapi: 3.2.0
info:
  title: Inference Service Healthz API
  version: 0.4.0
tags:
- name: Healthz
paths:
  /healthz:
    get:
      summary: Healthz
      operationId: healthz_healthz_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Healthz
components:
  securitySchemes:
    API_Key:
      type: http
      description: Bearer <api_key>
      scheme: bearer
