openapi: 3.2.0
info:
  title: Inference Service Metrics API
  version: 0.4.0
tags:
- name: Metrics
paths:
  /metrics:
    get:
      summary: Metrics
      operationId: metrics_metrics_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Metrics
components:
  securitySchemes:
    API_Key:
      type: http
      description: Bearer <api_key>
      scheme: bearer
